# Application bindings
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(solace-cmd-terminal-cwd)" tmux new
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(solace-cmd-terminal-cwd)"
bindd = SUPER SHIFT, RETURN, Browser, exec, solace-launch-browser
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER ALT SHIFT, F, File manager (cwd), exec, uwsm-app -- nautilus --new-window "$(solace-cmd-terminal-cwd)"
bindd = SUPER SHIFT, B, Browser, exec, solace-launch-browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, solace-launch-browser --private
bindd = SUPER SHIFT, M, Music, exec, solace-launch-or-focus spotify
bindd = SUPER SHIFT ALT, M, Music TUI, exec, solace-launch-or-focus-tui cliamp
bindd = SUPER SHIFT, N, Editor, exec, solace-launch-editor
bindd = SUPER SHIFT, D, Docker, exec, solace-launch-tui lazydocker
bindd = SUPER SHIFT, G, Signal, exec, solace-launch-or-focus ^signal$ "uwsm-app -- signal-desktop"
bindd = SUPER SHIFT, O, Obsidian, exec, solace-launch-or-focus ^obsidian$ "uwsm-app -- obsidian"

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
bindd = SUPER SHIFT, A, ChatGPT, exec, solace-launch-webapp "https://chatgpt.com"

# Overwrite existing bindings, like putting Solace Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Solace menu, exec, solace-menu
