$color = rgba({{ background_rgb }}, 1.0)
$inner_color = rgba({{ background_rgb }}, 0.8)
$outer_color = rgba({{ foreground_rgb }}, 1.0)
$font_color = rgba({{ foreground_rgb }}, 1.0)
$muted_color = rgba({{ foreground_rgb }}, 0.72)
$check_color = rgba({{ accent_rgb }}, 1.0)
$fail_color = rgba(255, 180, 171, 1.0)
