### Read more at config document: https://github.com/limine-bootloader/limine/blob/trunk/CONFIG.md
interface_branding: Solace Bootloader
interface_branding_color: 6298ea
interface_help_color: 36ceb8
interface_help_color_bright: ffffff
hash_mismatch_panic: no

term_background: ff00020a
backdrop: 00020a

# Terminal colors (Solace/Aether palette)
term_palette: 00020a;74661a;458d59;749951;3b6aa5;7b5daf;2c8478;ffffff
term_palette_bright: 54565a;9b8d19;66c677;9fd068;6298ea;bca0ec;36ceb8;ffffff

# Text colors
term_foreground: ffffff
term_foreground_bright: ffffff
term_background_bright: 1a1b23
