# Background and foreground colors
background = #181c22
foreground = #fffefd

# Standard colors
palette = 0=#181c22
palette = 1=#957172
palette = 2=#5e6360
palette = 3=#f8b280
palette = 4=#8c8d9a
palette = 5=#746b73
palette = 6=#50747f
palette = 7=#f3bd92

# Bright colors
palette = 8=#898c96
palette = 9=#c6aeaf
palette = 10=#939694
palette = 11=#fff5ee
palette = 12=#7d7e8b
palette = 13=#a8a0a8
palette = 14=#8aa6ad
palette = 15=#fffefd
